#!/usr/bin/python3

import argparse
import logging
import smtplib
import mimetypes
import os
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.audio import MIMEAudio
from email.mime.multipart import MIMEMultipart
from email import encoders





##########################################################
#
#
#              PUT YOUR CREDENTIALS HERE!
#                                 
#
(login, passwd) = ('<email@gmail.com>', '<the password>')
#
#
#
#
##########################################################








class EmailSender():
    """Simple client to send emails.

    Args:
        smtp_host (str): SMTP host ('smtp.gmail.com').
        smtp_port (int): SMTP host port (465).
        username (str): Client email ('yoremail@gmail.com'). This is also the sender.
        password (str): Your password ('Password123')
        log (logging, optional): Logging facility see logs (logging.getLogger()).

    """


    def __init__(self, smtp_host, smtp_port, username, password, log=None):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password

        if log != None:
            self.log = log
        else:
            self.log = logging.getLogger()

    def send(self, recipients, subject, body, attachments = []):
        """Send an email. Login is done with SMTP SSL.

        Args:
            recipients (list): List of emails to receive this message.
            subject (str): The email subject.
            body (str): The email text (body).
            atttachments (list, optional): List of files to be attached.

        Returns:
            True if successful, otherwise False.
        """
        result = True

        try:
            self.log.debug('creating client [{}] [{}] [{}]'.format(self.smtp_host, self.smtp_port, self.username))
            server = smtplib.SMTP_SSL(self.smtp_host, self.smtp_port)
            server.login(self.username, self.password)
        except:
            self.log.error("Login failed!")
            return False

        self.log.debug('building email from [{}] called [{}]'.format(self.username, subject))
        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From'] = self.username

        self.log.debug('attaching body [{}]'.format(body))
        txt = MIMEText(body)
        msg.attach(txt)

        try:
            if len(attachments) > 0:
                self.log.debug('loading attachments...')
        
            for path in attachments:
                self.log.debug('attaching [{}]'.format(path))
                self.load_attachment(path, msg)
        
        except:
            self.log.error("Failed to load attachments")
            return False

        mail_ascii = msg.as_string() #.encode('ascii', 'ignore').decode('ascii')

        self.log.debug('sending email...')
        for dst in recipients:
            sent = False # flag to control the result
            msg['To'] = dst
            try:
                server.sendmail(self.username, dst, mail_ascii)
                sent = True
            except:
                pass

            if not sent:
                self.log.error('sending failed to [{}]'.format(dst))
            else:
                self.log.debug('sending to [{}]'.format(dst))

            resutl = result and sent #increment global result

        server.quit()
        if result:
            self.log.debug('finished')
        else:
            self.log.warning('finished with errors')

        return result


    def load_attachment(self, filepath, message):
        """Load files as attachments. All files are 
        loaded with MIMEBase and encoded.

        Args:
            filepath (str): The file path.
            message (MIMEMultipart): The email to attach the file.
        """

        msg = None
        content_type, encoding = mimetypes.guess_type(filepath)
        self.log.debug("{}: content [{}] encoding [{}]".format(\
            filepath, content_type, encoding))
        
        if content_type != None:
            main_type, sub_type = content_type.split('/', 1)
            self.log.debug("{}: type [{}] sub [{}]".format(\
                filepath, main_type, sub_type))
        else:
            main_type = None
            sub_type = None

        fp = open(filepath, 'rb')
        msg = MIMEBase(main_type, sub_type)
        msg.set_payload(fp.read())
        encoders.encode_base64(msg)
        fp.close()

        filename = os.path.basename(filepath)
        self.log.debug('attachment filename [{}]'.format(filename))

        msg.add_header('Content-Disposition', 'attachment', filename=filename)
        message.attach(msg)


# Example
if __name__ == '__main__':
    if passwd == '<the password>'
        print("Please update this script 'login' and 'passwd' with your credentials!")
        exit(-2)

    ap = argparse.ArgumentParser()
    ap.add_argument('-s', '--subject', required=True,
        help='Subject of the email')
    ap.add_argument('-m', '--message', required=True,
        help='Message of the email (content)')
    ap.add_argument("-r", "--recipients", required=True,
        help='Comma separated list of emails recipients like: "email1@asdf.com,email2@asdf.com"')
    ap.add_argument("-a", "--attachments", required=False,
        help='Comma separated list of file paths to be attached like: "/home/user/msg.txt,/home/user/other.png"')
    ap.add_argument("-v", "--verbose", required=False, action='count', default=0, 
        help='Show detailed output')

    args = vars(ap.parse_args())

    # Create a log so we can see get some output (not mandatory, but wise)
    log = logging.getLogger("sender")
    if args['verbose'] > 0:
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.WARNING)

    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter('%(message)s'))
    log.addHandler(ch)

    # inform the user credentials
    sender = EmailSender("smtp.gmail.com", 465, login, passwd, log)

    if args['attachments'] != None:
        ret = sender.send(args['recipients'].split(','), args['subject'],  args['message'], args['attachments'].split(','))
    else:
        ret = sender.send(args['recipients'].split(','), args['subject'],  args['message'])
    
    if ret:
        exit(0)
    else:
        exit(-1)

